-- Luacheck for EsoChat (ESO Lua 5.1)

std = "lua51"

ignore = {
    "212", -- unused argument (ESO event callbacks)
    "631", -- line too long
    "122", -- mutating read-only globals (CHAT_SYSTEM hooks)
}

globals = {
    EsoChat = {
        other_fields = true,
    },
    EsoChatSettings = {
        other_fields = true,
    },
    SLASH_COMMANDS = {
        other_fields = true,
    },
}

read_globals = {
    "EVENT_MANAGER",
    "SLASH_COMMANDS",
    "d",
    "zo_callLater",
    "zo_strformat",
    "RequestOpenURL",
    "ZO_SavedVars",
    "ZO_ShallowTableCopy",
    "ZO_DeepTableCopy",
    "GetWorldName",
    "IsFriend",
    "IsIgnored",
    "IsPlayerInGroup",
    "IsUnitGrouped",
    "GetGroupSize",
    "GetNumGuilds",
    "GetGuildId",
    "GetNumGuildMembers",
    "GetGuildMemberInfo",
    "GetGuildMemberCharacterInfo",
    "GetGuildMemberIndexFromDisplayName",
    "GetDisplayName",
    "GetCurrentCharacterId",
    "GetUnitName",
    "GetUnitZone",
    "GetAddOnMetadata",
    "GetTimeStamp",
    "GetTimeString",
    "GetCVar",
    "GetSetting_Bool",
    "SETTING_TYPE_GAMEPAD",
    "GAMEPAD_SETTING_USE_KEYBOARD_CHAT",
    "ZO_ChatSystem_DoesPlatformUseGamepadChatSystem",
    "IsChatSystemAvailableForCurrentPlatform",
    "GetNumChatContainers",
    "GetNumChatContainerTabs",
    "GetChatContainerTabInfo",
    "IsChatContainerTabCategoryEnabled",
    "SetChatContainerTabCategoryEnabled",
    "SetChatContainerTabInfo",
    "AddChatContainer",
    "AddChatContainerTab",
    "RemoveChatContainerTab",
    "TransferChatContainerTab",
    "GetChatContainerColors",
    "SetChatContainerColors",
    "GetChatFontSize",
    "SetChatFontSize",
    "PlaySound",
    "SendChatMessage",
    "CopyToClipboard",
    "CreateControl",
    "ZO_ChatWindow",
    "ZO_PreHook",
    "SecurePostHook",
    "ZO_TabButton_Text_GetText",
    "ZO_TabButton_Text_SetText",
    "ZO_TabButton_Text_SetTextColor",
    "ZO_TabButton_Text_RestoreDefaultColors",
    "ZO_TabButton_Text_AllowColorChanges",
    "TAB_ALERT_TEXT_COLOR",
    "ZO_SECOND_CONTRAST_TEXT",
    "GetChannelCategoryFromChannel",
    "GetFrameTimeMilliseconds",
    "GuiRoot",
    "CT_LABEL",
    "CT_BACKDROP",
    "CT_EDITBOX",
    "DT_HIGH",
    "DL_OVERLAY",
    "BOTTOMRIGHT",
    "BOTTOMLEFT",
    "TOPLEFT",
    "KEY_UPARROW",
    "KEY_DOWNARROW",
    "GetAnchor",
    "SOUNDS",
    "CALLBACK_MANAGER",
    "LibAddonMenu2",
    "LibDebugLogger",
    "LibChatMessage",
    "LibMediaProvider",
    "LibPrice",
    "CHAT_ROUTER",
    "CHAT_SYSTEM",
    "SharedChatContainer",
    "ZO_ChatWindow",
    "CENTER_SCREEN_ANNOUNCE",
    "CSA_CATEGORY_SMALL_TEXT",
    "_G",
    "EVENT_ADD_ON_LOADED",
    "EVENT_PLAYER_ACTIVATED",
    "EVENT_PLAYER_DEACTIVATED",
    "EVENT_PLAYER_COMBAT_STATE",
    "EVENT_GROUP_MEMBER_JOINED",
    "EVENT_GROUP_MEMBER_LEFT",
    "EVENT_GROUP_UPDATE",
    "EVENT_CHAT_MESSAGE_CHANNEL",
    "EVENT_LOOT_RECEIVED",
    "CHAT_CHANNEL_SAY",
    "CHAT_CHANNEL_YELL",
    "CHAT_CHANNEL_WHISPER",
    "CHAT_CHANNEL_WHISPER_SENT",
    "CHAT_CHANNEL_ZONE",
    "CHAT_CHANNEL_ZONE_LANGUAGE_1",
    "CHAT_CHANNEL_PARTY",
    "CHAT_CHANNEL_SYSTEM",
    "CHAT_CHANNEL_GUILD_1",
    "CHAT_CHANNEL_GUILD_2",
    "CHAT_CHANNEL_GUILD_3",
    "CHAT_CHANNEL_GUILD_4",
    "CHAT_CHANNEL_GUILD_5",
    "CHAT_CATEGORY_SAY",
    "CHAT_CATEGORY_YELL",
    "CHAT_CATEGORY_WHISPER_INCOMING",
    "CHAT_CATEGORY_WHISPER_OUTGOING",
    "CHAT_CATEGORY_ZONE",
    "CHAT_CATEGORY_PARTY",
    "CHAT_CATEGORY_EMOTE",
    "CHAT_CATEGORY_SYSTEM",
    "CHAT_CATEGORY_GUILD_1",
    "CHAT_CATEGORY_GUILD_2",
    "CHAT_CATEGORY_GUILD_3",
    "CHAT_CATEGORY_GUILD_4",
    "CHAT_CATEGORY_GUILD_5",
    "CHAT_CATEGORY_OFFICER_1",
    "CHAT_CATEGORY_OFFICER_2",
    "CHAT_CATEGORY_OFFICER_3",
    "CHAT_CATEGORY_OFFICER_4",
    "CHAT_CATEGORY_OFFICER_5",
    "CHAT_CATEGORY_ZONE_ENGLISH",
    "CHAT_CATEGORY_ZONE_FRENCH",
    "CHAT_CATEGORY_ZONE_GERMAN",
    "CHAT_CATEGORY_ZONE_JAPANESE",
    "ZO_ChatSystem_DoesPlatformUseGamepadChatSystem",
    "MAIL_SEND",
    "CallSecureProtected",
    "GetCurrentMoney",
    "IsInGamepadPreferredMode",
    "unpack",
    "loadstring",
}
