describe("TabProfiles", function()
    it("seeds built-in profiles", function()
        EsoChat.db.tabs.profiles = {}
        EsoChat.TabProfiles.EnsureSeeds()
        assertTrue(EsoChat.db.tabs.profiles.Social ~= nil)
        assertTrue(EsoChat.db.tabs.profiles.Guild ~= nil)
        assertTrue(EsoChat.db.tabs.profiles.Whispers ~= nil)
        assertTrue(EsoChat.db.tabs.profiles.Combat ~= nil)
    end)

    it("saves a named profile", function()
        EsoChat.TabProfiles.EnsureSeeds()
        EsoChat.TabProfiles.Save("Custom", { CHAT_CATEGORY_SAY = true })
        assertTrue(EsoChat.db.tabs.profiles.Custom ~= nil)
        assertEqual(EsoChat.db.tabs.activeProfile, "Custom")
    end)

    it("CategoriesForApply disables all then enables seed", function()
        local cats = EsoChat.TabProfiles.CategoriesForApply({ CHAT_CATEGORY_SYSTEM = true })
        assertEqual(cats.CHAT_CATEGORY_SYSTEM, true)
        assertEqual(cats.CHAT_CATEGORY_SAY, false)
        assertEqual(cats.CHAT_CATEGORY_PARTY, false)
    end)
end)
